apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: orzen-api
  namespace: orzen-vision
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  tls:
    - hosts:
        - api.orzen.in
      secretName: orzen-api-tls
  rules:
    - host: api.orzen.in
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: backend-core
                port:
                  number: 80
